TIMESLOT_LENGTH = 0.01
EPISODES = 1  # number of episodes
T = 10  # horizon length
POSITION_SEED = 42
SCHEDULER = 3
"""
scheduler
1: Round Robin
2: My DQN
3: paper DQN
"""
PLANT_SAMPLE_TIME = 0.01
SENSOR_SAMPLE_TIME = 0.01
SAMPLE_TO_TIMESLOT_RATIO = TIMESLOT_LENGTH/PLANT_SAMPLE_TIME
PARAM_SEED = 42
NUM_PLANTS = 2
INSTABLE_PLANTS = 0
SCHEDULE_LENGTH = 2
PROTOCOL = 1
"""
protocol
1: TDMA
2: CSMA
"""